# Generated by Django 4.2.7 on 2023-12-15 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShieldBox',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.FloatField(max_length=50)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shieldbox_app.shieldbox')),
            ],
            options={
                'unique_together': {('name', 'device')},
            },
        ),
    ]
