# Generated by Django 4.2.7 on 2023-12-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shieldbox_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='temperaturesensor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='temperaturesensor',
            name='smoke_value',
            field=models.FloatField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='temperaturesensor',
            unique_together={('name', 'device', 'smoke_value')},
        ),
    ]
