# Generated by Django 4.2.7 on 2024-01-20 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shieldbox_app', '0002_alter_temperaturesensor_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperaturesensor',
            old_name='smoke_value',
            new_name='temp_value',
        ),
        migrations.AlterUniqueTogether(
            name='temperaturesensor',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='SmokeSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('smoke_value', models.FloatField(max_length=50)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shieldbox_app.shieldbox')),
            ],
        ),
        migrations.RemoveField(
            model_name='temperaturesensor',
            name='value',
        ),
    ]
