# Generated by Django 4.2.7 on 2024-01-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shieldbox_app', '0003_rename_smoke_value_temperaturesensor_temp_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smokesensor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='temperaturesensor',
            name='name',
        ),
    ]
