# Generated by Django 4.2.7 on 2024-01-21 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shieldbox_app', '0004_remove_smokesensor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturesensor',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
