# Generated by Django 4.2.8 on 2024-01-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shieldbox_app', '0005_temperaturesensor_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smokesensor',
            name='smoke_value',
            field=models.FloatField(),
        ),
    ]
