# Generated by Django 4.2.7 on 2024-01-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shieldbox_app', '0005_temperaturesensor_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smokesensor',
            name='smoke_value',
            field=models.FloatField(default=0.0, max_length=50),
        ),
        migrations.AlterField(
            model_name='temperaturesensor',
            name='temp_value',
            field=models.FloatField(default=0.0, max_length=50),
        ),
    ]
