# Generated by Django 4.2.7 on 2024-01-25 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shieldbox_app', '0006_alter_smokesensor_smoke_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smokesensor',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
