# Generated by Django 4.2.7 on 2023-12-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shieldbox_name', models.CharField(max_length=500)),
                ('sensors_data', models.FloatField()),
            ],
        ),
    ]
