# Generated by Django 4.2.7 on 2023-12-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorsdata',
            name='sensors_data',
        ),
    ]
