# Generated by Django 4.2.7 on 2023-12-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors_data', '0002_remove_sensorsdata_sensors_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorsdata',
            name='sensors_data',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
