# Generated by Django 4.2.7 on 2023-12-12 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nicname',
        ),
    ]
