# Generated by Django 4.2.7 on 2023-12-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nicname',
            field=models.CharField(default='default_nicname', max_length=55),
        ),
    ]
